### ISSUE TITLE
关于代码中的两个小问题

### ISSUE THREAD

**Issue by Light-lyy** [RUCAIBox/NCL#10]
1.在论文中，结构（structure）对比损失和原型（prototype）对比损失都包括用户侧和项目侧，总的损失是由用户侧损失与项目侧损失的加权和得到的，α为平衡系数。但在代码中，原型对比损失ProtoNCE_loss()是没有用户侧和项目侧的加权和的，而是直接相加相当于α=1：
proto_nce_loss = self.proto_reg * (proto_nce_loss_user + proto_nce_loss_item)

而结构对比损失ssl_layer_loss()却是有用户侧项目侧加权和的：
ssl_loss = self.ssl_reg * (ssl_loss_user + self.alpha * ssl_loss_item)

请问这是为什么呢？在论文的4.3.4中，讨论了**结构对比损失**中α的影响，并得出结论α大概为1时效果最好。如果按论文结论姑且把α=1作为结构对比损失的默认平衡系数，那也应该是ssl_layer_loss()无加权和、ProtoNCE_loss()有加权和吧？可在代码中却恰恰相反。

2.在代码中有个设置为20的warm_up_step，效果似乎是在前20代训练不把原型对比损失proto_loss算入损失函数进行参数优化，20代以后才算入。论文中似乎没介绍到这个warm_up_step，请问这个东西的作用是什么呢？如果不进行这一步会有什么后果？会对结果产生较大影响吗？

*3.你们论文中似乎有点小小的笔误，不过应该无伤大雅。在**表4**中，Lightgcn在MovieLens-1M上的Recall@10、NDCG@10和在Yelp上的Recall@10、NDCG@10分别是 0.1888、0.2526、0.0833、0.0601。然而根据**表2**的结果，Lightgcn的这四个数据应该是0.1876 、0.2514、0.0730、0.0520，而0.1888、0.2526、0.0833、0.0601这四个数是属于SGL的对应结果。此外，DGCF在MovieLens-1M上的Recall@10、NDCG@10根据表4结果是0.1853、0.2500，而根据表2结果是0.1881、0.2520，也存在小小的不一致。

**Comment by linzihan-backforward** [comment]
1. 因为我们发现在其对原型损失的效果不大，所以在代码中直接将其恒定设置为1，而结构损失中的alpha我们在参数敏感性实验中对其作用进行了探讨。
2. 这个warm_up的作用是让训练更稳定，对于结果影响不大，只是一个小trick，所以没有在论文中提
3. 感谢你的细致阅读，这确实是我们的笔误。
