### ISSUE TITLE
关于论文内容的问题

### ISSUE THREAD

**Issue by Rvlis** [RUCAIBox/NCL#11]
作者你好，我对论文中图2 Overall framework 中的结构邻居有些疑惑，论文中说的将GNN网络中偶数层输出作为正样本对，也就是一个节点要和它的偶数跳邻居构成正样本对，为什么我看图中画的正负样本对都是1-近邻呢，谢谢解答

**Comment by hyp1231** [comment]
感谢关注！这里我们确实解释得不是很清楚，图 2 中的图是 user-user 的图，如果两个 user 共同购买了一个商品，则在 user-user 图中就会相连。所以这个图不是 user-item 二部图，画的正负样本对实际是 user-item 交互二部图的 2-近邻。

**Comment by Rvlis** [comment]
谢谢作者回复。
请问在这个图中，锚点指的是蓝色节点吗，如果是的话，为什么loss function分子分母部分都是2-近邻呢，我的理解是正样本对是2-近邻，负样本对不是邻居或者相距很远的同质节点，因为刚接触CL不久，所以有些问题还不清楚，再次感谢作者解答

**Comment by hyp1231** [comment]
为了效率上的考虑，我们用中心节点 GNN 偶数层的表示作为 2-近邻表示（蓝色），正例 pair 是中心节点 GNN 偶数层（蓝色）与初始表示（白色），负例 pair 是 GNN 偶数层（蓝色）与其他同质节点的初始表示（红色）。

您提到的方式在概念上也符合本文设立的自监督目标，不过我们也没有具体实验过，您也可以积极探索不同对比目标对效果的影响。

**Comment by Rvlis** [comment]
好的，可能是因为我还没认真研究源码就直接来提问了，十分感谢作者的回复
