### ISSUE TITLE
请教可视化嵌入图怎么画？

### ISSUE THREAD

**Issue by 2391134843** [RUCAIBox/NCL#12]
![image](https://user-images.githubusercontent.com/33213327/170445977-69d349e5-147f-4f3c-9a1f-c228949b2558.png)
您好！您的idea非常 nice ~， 我想请教一下 图6的商品的嵌入可视化我应该如何画？

**Comment by hyp1231** [comment]
您好，请参考 #8。

**Comment by 2391134843** [comment]
谢谢！！
