### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by malajikuai** [RUCAIBox/NCL#13]
您好！
         代码中提及用到了faiss-gpu1.7.1，但是我发现cuda10.2的faiss-gpu1.7.1一直安装不上，conda换源也没用，用anaconda search -t conda faiss-gpu发现并没有faiss-gpu1.7.1的包，不知道作者是怎么安装的？

**Comment by hyp1231** [comment]
建议检查（1）python 版本，我们使用的是 3.7（2）NVIDIA Driver 的版本，我们使用的是 455.23

我们安装环境的命令如下（已经换成 THU 源）
```bash
conda create -n ncl python=3.7
conda activate ncl
conda install pytorch=1.7.1 cudatoolkit=10.1 -c pytorch
conda install faiss-gpu=1.7.1 -c pytorch
```

此外其实我觉得版本不用卡得太死，安装一个比较新的 faiss-gpu 就可以了，不必严格限制 1.7.1。比如可以参考 https://github.com/RUCAIBox/NCL/issues/5#issuecomment-1094531290 的环境。

**Comment by malajikuai** [comment]
谢谢，已经解决环境问题。
