### ISSUE TITLE
关于消融实验

### ISSUE THREAD

**Issue by malajikuai** [RUCAIBox/NCL#14]
我注意到作者在4.3.1中提到为了验证不同邻居的作用，进行了两个消融实验，分别是只用结构邻居和只用语义邻居，实验结果是NCL>只用结构邻居>只用语义邻居>LightGCN，但是我在数据集ML-1M上进行实验的时候是，语义邻居的结果奇差（比Light GCN还差），不知道作者在这里是不是进行了一些参数细微的调整？如果是，方便告知如何调整的吗？

**Comment by hyp1231** [comment]
您好！感谢关注。

在进行消融实验时，我们对每个变种版本也进行了 Sec. 4.1.4 中描述的超参数调优，它们的最优参数可能和主模型不同，建议您调优参数后再进行比较。

**Comment by kaishuibujiatang** [comment]
您好，我想问一下代码应该分别注释或修改那一部分，分别进行消融结构邻居和语义邻居实验呢？

> 您好！感谢关注。
> 
> 在进行消融实验时，我们对每个变种版本也进行了 Sec. 4.1.4 中描述的超参数调优，它们的最优参数可能和主模型不同，建议您调优参数后再进行比较。

**Comment by kaishuibujiatang** [comment]
> 您好，请想问一下代码应该分别注释或修改那一部分，进行消融结构邻居和语义邻居实验呢？

您好，请想问一下代码应该分别注释或修改那一部分，进行消融结构邻居和语义邻居实验呢？

> 我注意到作者在4.3.1中提到为了验证不同邻居的作用，进行了两个消融实验，分别是只用结构邻居和只用语义邻居，实验结果是NCL>只用结构邻居>只用语义邻居>LightGCN，但是我在数据集ML-1M上进行实验的时候是，语义邻居的结果奇差（比Light GCN还差），不知道作者在这里是不是进行了一些参数细微的调整？如果是，方便告知如何调整的吗？

您好，请想问一下代码应该分别注释或修改那一部分，进行消融结构邻居和语义邻居实验呢？

**Comment by kaishuibujiatang** [comment]
> 我注意到作者在4.3.1中提到为了验证不同邻居的作用，进行了两个消融实验，分别是只用结构邻居和只用语义邻居，实验结果是NCL>只用结构邻居>只用语义邻居>LightGCN，但是我在数据集ML-1M上进行实验的时候是，语义邻居的结果奇差（比Light GCN还差），不知道作者在这里是不是进行了一些参数细微的调整？如果是，方便告知如何调整的吗？

您好，请想问一下代码应该分别注释或修改那一部分，进行消融结构邻居和语义邻居实验呢？

**Comment by hyp1231** [comment]
Close as solved in #17.
