### ISSUE TITLE
数据集描述问题

### ISSUE THREAD

**Issue by sanyu6** [RUCAIBox/NCL#15]
![5bc6f484f5b176d71b54c03e42aa767](https://user-images.githubusercontent.com/96935888/175278451-ca40fa08-0b66-4f1a-af6e-aa95d1d17e88.png)
你在论文中描述的Users和Items 个数是否有问题，因为我看到代码将 id 为 0 的位置是不使用的，所以你的User和Item个数是不是都多了1，但是alibaba数据集的统计是正确的。

**Comment by hyp1231** [comment]
感谢指出这个问题！除了 Alibaba 数据集，其他的 Users 和 Items 的数量确实都多了 1。

**Comment by SunYuMs** [comment]
好的，谢谢了

**Comment by malajikuai** [comment]
另外这里的item是不是都重新映射了一个新的编号啊？

**Comment by linzihan-backforward** [comment]
> 另外这里的item是不是都重新映射了一个新的编号啊？

我们的代码基于RecBole实现，RecBole会对所有的user和item做remap，将其映射到从1开始连续ID，如果想要获取到原始ID，可以参考RecBole中的方法(recbole/utils/case_study.py)，如果有问题欢迎到RecBole项目下提问。
