### ISSUE TITLE
4.3.7 Applying NCL on Other GNN Backbones.

### ISSUE THREAD

**Issue by kaishuibujiatang** [RUCAIBox/NCL#16]
- 您好，可以分享一下NCL在其他模型上应用的代码嘛，非常感谢

**Comment by hyp1231** [comment]
Hi! 可以尝试将本项目下的 [ncl.py](https://github.com/RUCAIBox/NCL/blob/master/ncl.py) 中的函数 `forward`, `calculate_loss`, `full_sort_predict` 替换为 RecBole 的对应模型的实现，例如： [ngcf.py](https://github.com/RUCAIBox/RecBole/blob/master/recbole/model/general_recommender/ngcf.py) 和 [dgcf.py](https://github.com/RUCAIBox/RecBole/blob/master/recbole/model/general_recommender/dgcf.py)。

**Comment by kaishuibujiatang** [comment]
好的，感谢感谢
