### ISSUE TITLE
如何进行消融实验

### ISSUE THREAD

**Issue by kaishuibujiatang** [RUCAIBox/NCL#17]
您好，想请问一下如何分别进行结构邻居和语义邻居消融实验？
这部分代码不是很懂**def _train_epoch(self, train_data, epoch_idx, loss_func=None, show_progress=False):**，想请教一下该分别修改哪一部分的代码，感谢感谢

**Comment by linzihan-backforward** [comment]
您好，可以直接将calculate_loss()函数中对应的Loss设置为0即可，在ncl.py文件的241行。

**Comment by kaishuibujiatang** [comment]
好的，感谢感谢。
