### ISSUE TITLE
valid数据和test数据结果相差很大

### ISSUE THREAD

**Issue by kaishuibujiatang** [RUCAIBox/NCL#18]
![NCL](https://user-images.githubusercontent.com/90997061/186566811-7d8b9de5-e655-4690-944a-f8d64abc9cc1.png)
你好，想请教一下，为啥这两个结果会相差这么大

**Comment by hyp1231** [comment]
你好，为了严格的评测，那些在 validation set 中出现的 interaction 会在 test set 的评测中被移除，因此导致 general recommendation 这个类别中的 test result 结果通常比 valid 好。也可以参考 [[link]](https://recbole.io/docs/user_guide/usage/qa.html) 的 Q2。

**Comment by kaishuibujiatang** [comment]
好的感谢
