### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by yuanzhongfei** [RUCAIBox/NCL#2]
你好，我想问一下为什么用gpu，显示cuda超出内存呢，我改了下batch_size也没有效果

**Comment by hyp1231** [comment]
你好，可以提供一下以下信息嘛？

* 系统版本
* gpu 显存大小
* 数据集
* 运行的指令

**Comment by yuanzhongfei** [comment]
> 你好，可以提供一下以下信息嘛？
> 
> * 系统版本
> * gpu 显存大小
> * 数据集
> * 运行的指令

版本：Linux omnisky 4.15.0-47-generic #50~16.04.1-Ubuntu SMP Fri Mar 15 16:06:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage /Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+====
|   0  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
| 58%   61C    P2   151W / 250W |  10321MiB / 10989MiB |     30%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:03:00.0 Off |                  N/A |
| 69%   67C    P2   153W / 250W |   4527MiB / 10989MiB |     85%      Default 

数据集就是这个里面的lm-1m
就是使用 python main.py --dataset=lm-1m

**Comment by hyp1231** [comment]
你好，根据提供的信息，推测可能是服务器里 0 号 GPU 已经有程序在占用显存了（只剩 600+ M 可供使用）。而使用默认参数在 ml-1m 上运行 NCL 需要至少 2773MiB 的显存空间。

因此或者等 0 号 GPU 显存充足时重新运行，或运行下述命令使用 1 号 GPU 运行 NCL。

```bash
CUDA_VISIBLE_DEVICES=1 python main.py --dataset=ml-1m --gpu_id=1
```

**Comment by yuanzhongfei** [comment]
> 你好，根据提供的信息，推测可能是服务器里 0 号 GPU 已经有程序在占用显存了（只剩 600+ M 可供使用）。而使用默认参数在 ml-1m 上运行 NCL 需要至少 2773MiB 的显存空间。
> 
> 因此或者等 0 号 GPU 显存充足时重新运行，或运行下述命令使用 1 号 GPU 运行 NCL。
> 
> ```shell
> CUDA_VISIBLE_DEVICES=1 python main.py --dataset=ml-1m --gpu_id=1
> ```

哦哦，好的谢谢

**Comment by hyp1231** [comment]
先关闭了。如果还有疑问，可以随时评论。
