### ISSUE TITLE
prototype contrastive learning相关问题请教，感谢回复

### ISSUE THREAD

**Issue by topDreamer** [RUCAIBox/NCL#21]
您好，有个问题存在疑问，请教一下，非常感谢：
对于prototype CL，看相关文章介绍，获取prototype表示的计算方式常见的有两种：
1、通过对训练集进行k-means聚类产生K类prototype表示；
2、对训练集中的每一类的samples进行求平均获得每一类对应的prototype表示；
对于一个anchor sample，第二种构建positive pair的方式是(anchor, prototype_2),其中prototype_2是anchor对应的class类别所计算产生的prototype；Negative pair(anchor，prototype_2_),prototype_2_是与anchor不对应的class类别的prototype；

问题：
1、请问对第一种方式(获得聚类的结果后)是如何构建正负pair呢？
2、请问是否有尝试第二种计算prototype的表示的方法，有什么区别？

**Comment by linzihan-backforward** [comment]
您好，您提到的第二种方法需要用到类别标签，只适用于有监督对比学习中。在协调过滤场景下，我们对用户/商品的表征向量进行K-means聚类，并将每一个聚类中心作为此聚类内所有用户/商品的prototype，此时正负样本分别来自于同一聚类和不同聚类的prototype。不知此解释是否能回答您的疑问。

**Comment by topDreamer** [comment]
非常感谢答疑！
