### ISSUE TITLE
faiss.kmeans

### ISSUE THREAD

**Issue by Doctor-JZL** [RUCAIBox/NCL#22]
你好，借鉴了你的代码做实验，发现进行faiss.kmeans聚类时报了这个错误，查了好久都没解决，请问你遇到过这个问题吗
RuntimeError: Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&) at /__w/faiss-wheels/faiss-wheels/faiss/faiss/gpu/StandardGpuResources.cpp:452: Error: 'err == cudaSuccess' failed: StandardGpuResources: alloc fail type TemporaryMemoryBuffer dev 0 space Device stream 0x55c6522666a0 size 1610612736 bytes (cudaMalloc error out of memory [2])

**Comment by Doctor-JZL** [comment]
已解决

**Comment by Jaccelerator** [comment]
请问您当时是怎么解决的呢？我也时不时会报这个错误。
