### ISSUE TITLE
请问你们的yelp数据集

### ISSUE THREAD

**Issue by Light-lyy** [RUCAIBox/NCL#25]
是用其他论文广泛使用的yelp2018，还是用完整版的yelp数据集呢？

**Comment by hyp1231** [comment]
我们用的是当时 RecBole 放出来的处理好的 yelp 数据集，应该是 2020 版本的。最近 RecBole 更新了处理好的数据，2018/20/21/22 以及完整版都已放出，您也可以在其他版本的数据上进行实验。

**Comment by Light-lyy** [comment]
呃，我从https://github.com/RUCAIBox/RecSysDatasets 给出的yelp2020链接里下载了压缩包并解压出review.json，核实了里面确实有8,021,122条评论信息，然后参考NCL的yelp.yaml设置，取出stars大于等于3的评论，再循环去除交互数小于15的用户和项目，保证最后剩下的用户和项目的交互数都大于等于15。

但最后我得到的用户数、项目数、交互数分别是42700、28996、1629741，与论文里写的45478、30709、1777765相差甚多，不知道是不是我处理方法有问题。但我处理的gowalla数据集是能得到和你们一样的结果的（29858、40988、1027464）。

我比较希望能使用和你们一致的数据集，这样我在数据集上跑出的别的模型的结果就可以参考你们论文的Table 2了

**Comment by Light-lyy** [comment]
顺便再问一下你们使用的amazon数据集是2014的还是2018的呢，我在RecSysDatasets那里也看到有这两个版本

**Comment by hyp1231** [comment]
> 呃，我从https://github.com/RUCAIBox/RecSysDatasets 给出的yelp2020链接里下载了压缩包并解压出review.json，核实了里面确实有8,021,122条评论信息，然后参考NCL的yelp.yaml设置，取出stars大于等于3的评论，再循环去除交互数小于15的用户和项目，保证最后剩下的用户和项目的交互数都大于等于15。
> 
> 但最后我得到的用户数、项目数、交互数分别是42700、28996、1629741，与论文里写的45478、30709、1777765相差甚多，不知道是不是我处理方法有问题。但我处理的gowalla数据集是能得到和你们一样的结果的（29858、40988、1027464）。
> 
> 我比较希望能使用和你们一致的数据集，这样我在数据集上跑出的别的模型的结果就可以参考你们论文的Table 2了

我尝试复现了一下，使用 RecBole 的数据处理是可以复现出论文的统计数据的。我刚刚更新了一下 yelp 的配置（https://github.com/RUCAIBox/NCL/commit/0aaf7c8d5a1036d9493c47b5cb6888ca20c814a9 ，主要是对齐云端数据集的列名），通过下述步骤：
```bash
git clone git@github.com:RUCAIBox/NCL.git
cd NCL/
python main.py --dataset yelp # 会报错，因为云端自动下载的数据里新增了 yelp.tip，recbole1.0.1 处理不了
rm dataset/yelp/yelp.tip
python main.py --dataset yelp # 成功运行
```
会输出下述结果
```
...
11 Nov 14:14    INFO  yelp
The number of users: 45478
Average actions of users: 39.09151878971788
The number of items: 30709
Average actions of items: 57.89256871173635
The number of inters: 1777765
The sparsity of the dataset: 99.87270617988263%
Remain Fields: ['user_id', 'item_id', 'rating']
...
```

和论文中表格一致。如果您希望使用其他框架，可以把此时的数据导出，以避免数据处理过程的不一致。

**Comment by hyp1231** [comment]
> 顺便再问一下你们使用的amazon数据集是2014的还是2018的呢，我在RecSysDatasets那里也看到有这两个版本

应该是 2014 版本的。

**Comment by Light-lyy** [comment]
我已经找到我们处理结果不一致的原因了：问题出在你们没有去除重复交互。举个极端例子，不去除重复交互的情况下，某个用户与同一个项目重复交互15次，按你们的方法这个用户不会被筛除。然而这个用户实际上只与一个项目交互过，体现在二分图中就是只有一个邻居，理应筛去。之前也有[issue](https://github.com/RUCAIBox/NCL/issues/4)指出未去除重复交互的问题。

我也尝试了不去除重复交互，便得到了与你们相同的结果。而我之前的结果是去除了重复交互的。最后，还是很感谢您能在百忙之中回复我的问题，祝您一切顺利^_^
