### ISSUE TITLE
parameter setting

### ISSUE THREAD

**Issue by Iwillcome** [RUCAIBox/NCL#27]
There are some problem about parameter setting. In the paper,the range of regularization λ3 did't introducted. Meantime, i find  it is different for different dataset in yaml file, for example, the λ3 is 1e-6 and 1e-4 in amazon-books and yelp datasets respectively. Other paramter setting also different the description in paper. So, I want know the range of λ3 and the current λ3 whether or notthe best value in experiment.

**Comment by linzihan-backforward** [comment]
Hi! λ3 is the coefficient of L2 regularization which is not the main contribution of our model, so we omit the range in our paper. The current λ3 in our yaml file is the best value and the range of λ3 is [1e-3, 1e-4, 1e-5, 1e-6].

**Comment by Iwillcome** [comment]
Thanks for you response. now i understand the λ3 , lr and other parameters are the best value for NCL. Thanks you again.
