### ISSUE TITLE
关于warm_up_step的疑问

### ISSUE THREAD

**Issue by LiuZS10** [RUCAIBox/NCL#29]
您好！
在您的trainer.py中，我注意到(line150-151):
` if epoch_idx < self.config['warm_up_step']:  
                    losses = losses[:-1]`
能否再解释一下，当epoch_idx < warm_up_step时，losses只取前两个损失的原因呢，谢谢

**Comment by linzihan-backforward** [comment]
在刚开始训练的前几个epoch，表示向量中还未完全被优化，这时候进行的聚类和原型对比是有很多噪声且不稳定的，所以在训练初始阶段丢掉了原型对比loss

**Comment by LiuZS10** [comment]
> 在刚开始训练的前几个epoch，表示向量中还未完全被优化，这时候进行的聚类和原型对比是有很多噪声且不稳定的，所以在训练初始阶段丢掉了原型对比loss
谢谢回复！
另外，我在ml-1m和gowalla两个数据集上运行了代码，根据tensorboard生成的loss图像发现，Loss/Train1，也就是ssl_loss，会出现先下降，突然变得很大后在下降的情况，请问作者在之前的实验中是否有遇到过这种情况呢？谢谢

**Comment by linzihan-backforward** [comment]
> 

这是正常的现象，初始阶段表示向量为随机初始化，ssl_loss会很小，当表示向量被bpr_loss进行一定优化后，ssl_loss才会突然增大。

**Comment by LiuZS10** [comment]
> > 
> 
> 这是正常的现象，初始阶段表示向量为随机初始化，ssl_loss会很小，当表示向量被bpr_loss进行一定优化后，ssl_loss才会突然增大。

谢谢回复！
