### ISSUE TITLE
loss function

### ISSUE THREAD

**Issue by Iwillcome** [RUCAIBox/NCL#30]
Dear Author:
     There are some problems with the loss function, and I sincerely wish can get the answer to the question.
      when I study the code, some prebloe for code is eremgeen. The BPR loss in the paper means up all sample loss in every min-batch, but it is different from the described in equation 5. But it isn't the key to the problem. However, The contrastive learning sums up the contrastive loss of all samples. I didn't this difference will bring what influence for the result. 
                                                                                                                                                                           Good Wish!

**Comment by linzihan-backforward** [comment]
Hi, for the loss function, sum up or mean up the loss on all samples of a mini-batch is equivalent. As the batch-size is fixed, they both can work well when we find proper coefficients.

**Comment by Iwillcome** [comment]
I understand the thought, The different methods just result in different parameters. But why select node self-embedding as the anchor?  why not is the odd layer embedding, For example, the second layer? Is the different anchor embedding for the result is same?

**Comment by linzihan-backforward** [comment]
We select the self-embedding as the anchor because it is the original representation of users and items. The embedding from second layer combines the feature of many nodes which is unbefitting. Our setting can get the best results based on our experiments. We encourge you to make further research to find better structure!

**Comment by Iwillcome** [comment]
Dear Author:
  Thinks you answer, I understand why the NCL slect the self-embedding as the anchor. Think you!
