### ISSUE TITLE
Result problem 

### ISSUE THREAD

**Issue by DoJerryChen** [RUCAIBox/NCL#31]
Dear Authors:
  The NCL realize by recbole make a great progress compared with the SATO model.  However, when i read papre, some question are occur. The result of NCL poorer than the most model in XSImGCL (XSimGCL: Towards Extremely Simple Graph Contrastive Learning for Recommendation, Github URL:https://github.com/Coder-Yu/SELFRec ), and even thougth can't over SGL. The two different implement the model and get the result in different dataset. But, The result is poor, THe NCL just excel LightGCN.

Result fellow:
![image](https://user-images.githubusercontent.com/56619833/208388276-8fd78cad-27ad-411a-a546-de2c23d75466.png)

**Comment by linzihan-backforward** [comment]
Hi. We don't know how they reproduce NCL in their code. there are several vital hyper-parameters such as: batch_size, ssl_reg, tau. You can run both our code and their code locally. Carefully search those hyper-parameter and we think the results would be better than they report.

**Comment by DoJerryChen** [comment]
Dear author:
     If we free, i will run the program based on the advice provide by you.
