### ISSUE TITLE
ProtoNCE_Loss

### ISSUE THREAD

**Issue by Zhuohan007** [RUCAIBox/NCL#34]
Hello！When calculating ProtoNCE_loss, why do you use the embedding of the 0th layer of the node instead of the embedding after the k-layer is propagated?  Please reply if you see it.

**Comment by linzihan-backforward** [comment]
Hi~ You can reference [this issue](https://github.com/RUCAIBox/NCL/issues/30#issuecomment-1352458703) to get the answer.
