### ISSUE TITLE
A small question about the reported number.

### ISSUE THREAD

**Issue by SpaceLearner** [RUCAIBox/NCL#35]
Dear authors of NCL， I find two problems of the reported numbers of dataset Alibaba-iFashion in the paper:

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/23473264/212627463-32917441-b806-46bc-bb39-b0412aee4afe.png">

Maybe you could make a refinement.

**Comment by linzihan-backforward** [comment]
Hi ! Thanks for your careful reading. They are all the typos in our paper. The right numbers are : 

BPR Recall@10 0.0303
NeuMF Recall@10 0.0182
LightGCN NDCG@10 0.0246
LightGCN NDCG@20 0.0301

**Comment by SpaceLearner** [comment]
Thanks a lot for your in time reply.
