### ISSUE TITLE
模型运行问题

### ISSUE THREAD

**Issue by kbk12** [RUCAIBox/NCL#36]
您好，请问一下报这个错误ImportError: cannot import name 'set_color'，跟recbole模块中没有set_ color方法有关吗，怎么解决

**Comment by hyp1231** [comment]
您好，请问有详细一些的报错记录吗？我们确实也没什么头绪。

目前知道的是 recbole.utils 是实现了一个叫 `set_color` 的函数的，或许可以检查一下其他 python 库是否有同名函数，或者 recbole 的版本是否为 1.0.1。
