### ISSUE TITLE
About alibaba dataset

### ISSUE THREAD

**Issue by downeykking** [RUCAIBox/NCL#38]
hello, i wonder to ask in alibaba dataset, there has `300000 users`, and in the original dataset, alibaba-ifasion has `3569112 users`. How do you get the `300000 users` because neither the interaction filter nor value field filted has been done from `alibaba.yaml`. Do you just follow the paper SGL, `Alibaba-iFashion is more sparse, where we randomly sample 300k users and use all their interactions over the fashion outfits.` ? Thanks in advance!

**Comment by linzihan-backforward** [comment]
Yes, we just follow the paper SGL and use the dataset that they provide to make fair comparison.

**Comment by downeykking** [comment]
> Yes, we just follow the paper SGL and use the dataset that they provide to make fair comparison.

Got it, thanks!
