### ISSUE TITLE
请教一下latex论文符号

### ISSUE THREAD

**Issue by zzoxi** [RUCAIBox/NCL#44]
![image](https://github.com/RUCAIBox/NCL/assets/48060836/903caec6-7c66-4cfb-b7f0-379c944ee433)
请问一下这种形式的U和I不知道如何在latex中打出？使用\mathcal{U}样式并不相同？

**Comment by hyp1231** [comment]
您好，是 `mathcal`，可能是 LaTeX 渲染问题？

原文的 tex 是 `$\mathcal{G} = \{ \mathcal{V}, \mathcal{E} \}$, where $\mathcal{V} = \{ \mathcal{U} \cup \mathcal{I}\}$`。
