### ISSUE TITLE
参数设置请教

### ISSUE THREAD

**Issue by shcw0405** [RUCAIBox/NCL#45]
我们注意到您论文中sgl模型与sgl原文结果差距较大，想向您请教一下您调的sgl参数

**Comment by hyp1231** [comment]
SGL 原文的数据处理是：we use the same 10-core setting for Yelp2018 and Amazon-Book ... split the interactions into training, validation, and testing set with a ratio of 7:1:2 ...

而 NCL 的数据处理主要使用 RecBole 框架自带的数据划分模块，且数据处理为：For Yelp and Amazon Books datasets, we filter out users and items with fewer than 15 interactions to ensure data quality. ...  For each dataset, we randomly select 80% of interactions as training data and 10% of interactions as validation data. The remaining 10% interactions are used for performance comparison.

所以两篇论文的实验设置并不相同，直接比较两篇论文的指标数值并无实际意义。

**Comment by shcw0405** [comment]
我们希望复现您文章中sgl的结果，以做进一步分析，想请教下具体参数和模型设置

**Comment by hyp1231** [comment]
我们跑 baseline 时使用的 SGL 模型文件是 [sgl.py](https://github.com/RUCAIBox/RecBole/blob/master/recbole/model/general_recommender/sgl.py)，应该比较好迁移到当前代码框架下。

在跑 baseline 时，我们汇报的是超参调优后的结果，但是当时好像没有记录最优参数和调参范围，推荐您尝试使用 RecBole 自带的超参调优工具。具体可参考 #40 。
