### ISSUE TITLE
验证集batch_size参数设置问题

### ISSUE THREAD

**Issue by deepML2020** [RUCAIBox/NCL#47]
你好，在设置验证集的参数eval_batch_size: 2048后，不起作用，debug显示验证集batch大小为1，不过训练集的train_batch_size参数却有效，这是咋回事？该如何调整验证集batch，求解答

**Comment by hyp1231** [comment]
你好！RecBole 里 General model 的 batch size 代表评测时的 interaction 数量，且 RecBole 会调整 General model 评测时的 batch size 为 item 个数的整数倍，以保证同一个 user 的所有 interaction 出现在同一个 batch 中。

因此我们建议 General model 的 batch size 设置得大一些，比如如果想大概一个 batch 测 K 个 users，则需要设置 eval_batch_size 至少为 K*n_items 这么大。

**Comment by deepML2020** [comment]
好的，感谢解答
