### ISSUE TITLE
想请问一下这么模型怎么对超参数进行网格搜索？

### ISSUE THREAD

**Issue by njt123123** [RUCAIBox/NCL#49]

**Comment by hyp1231** [comment]
目前模型已经集成到 RecBole 主框架中 [ncl.py](https://github.com/RUCAIBox/RecBole/blob/master/recbole/model/general_recommender/ncl.py)，您可以直接使用 RecBole 的超参数搜索功能 [API Doc](https://recbole.io/docs/user_guide/usage/parameter_tuning.html)。
