### ISSUE TITLE
想问一下Figure4中根据稀疏度把用户分组是用什么方法实现的？

### ISSUE THREAD

**Issue by njt123123** [RUCAIBox/NCL#52]

**Comment by hyp1231** [comment]
我们论文中的描述是：
> Concretely, we split all the users into five groups based on their interaction number, while keeping the total number of interactions in each group constant.

相关的代码实现请参考 #33

**Comment by njt123123** [comment]
> 我们论文中的描述是：
> 
> > 具体来说，我们根据用户的交互次数将所有用户分为五组，同时保持每组中的交互总数不变。
> 
> 相关的代码实现请参考 #33

好的，感谢，请问可以提供一下对比模型的参数吗

**Comment by hyp1231** [comment]
参考 https://github.com/RUCAIBox/NCL/issues/45#issuecomment-1670616434
> 在跑 baseline 时，我们汇报的是超参调优后的结果，但是当时好像没有记录最优参数和调参范围，推荐您尝试使用 RecBole 自带的超参调优工具。具体可参考 https://github.com/RUCAIBox/NCL/issues/40 。

**Comment by njt123123** [comment]
> 参考 [#45 (comment)](https://github.com/RUCAIBox/NCL/issues/45#issuecomment-1670616434)
> 
> > 在跑 baseline 时，我们汇报的是超参调优后的结果，但是当时好像没有记录最优参数和调参范围，推荐您尝试使用 RecBole 自带的超参调优工具。具体可参考 #40 。

好的，感谢

**Comment by njt123123** [comment]
> 参考 [#45 （comment）](https://github.com/RUCAIBox/NCL/issues/45#issuecomment-1670616434)
> 
> > 在跑 baseline 时，我们汇报的是超参调优后的结果，但是当时好像没有记录最优参数和调参范围，推荐您尝试使用 RecBole 自带的超参调优工具。具体可参考 #40 。

可提供一下超参数调优的代码吗？自己弄有点麻烦
