### ISSUE TITLE
statistical significance test

### ISSUE THREAD

**Issue by h12345jack** [RUCAIBox/NCL#6]
您好，可以请问table2的假设检验应该如何进行吗？
是选取不同的seed吗？请问需要选取多少的seed重复实验？

谢谢

**Comment by hyp1231** [comment]
您好，是的，我们选取了 10 个随机种子，然后采用了 paired t-test 方法进行显著性检验。

**Comment by h12345jack** [comment]
好的，非常感谢您的回复。
